#! /usr/bin/env python

# entry point.

# in future, should allow to run commands directly, 
# right now 

import logging
import sys, os
from traceback import format_exc

logging.basicConfig(level=logging.DEBUG)
from Server import app

print "do not use this program. call 'python Server.py' instead."
os.execlp("python", "python", "./Server.py")
sys.exit(1)

if len(sys.argv) < 2:
  print "usage: serial_rent [server|client|standalone]"
  sys.exit(1)

args = sys.argv[1:]
args.reverse()

try:
  arg = args.pop()
  print arg
  if arg == "server":
    app.run()
  elif arg == "client":
    pass
  elif arg == "standalone":
    arg = args.pop()
    print app.request(arg).data
  else:
    raise RuntimeError("cmdl args")
except Exception as ex:
  print format_exc(ex)

